### ISSUE TITLE
Multiple CSS Selectors

### ISSUE THREAD

**Issue by cyouh95** [jrs4/colmar#4]
Great that you are using comma separated selectors to specify shared properties for multiple elements. Alternatively, since you want to specify these properties for most of the elements on your page, you could use `body` as the selector so that all elements would inherit these - and override these properties for the few elements that you want to have a different color, etc.

```css
body {
  color: #444444;   
  text-decoration: none;
  ...
}
```

https://github.com/jrs4/colmar/blob/master/resources/css/style.css#L87
